apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webapp-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: webapp-secret

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: webapp-db-password

    - secretKey: API_KEY
      remoteRef:
        key: webapp-api-key